# Generated by Django 5.1.2 on 2024-10-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneaker',
            old_name='name_sneakers',
            new_name='name',
        ),
    ]
